version: '3.9'
services:
  cache:
    image: redis:7-alpine
    user: "1000:1000"
    restart: on-failure
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local