version: '3.9'
services:
  app:
    image: local/akito13/zoominvitr:local
    container_name: zoominvitr
    user: "1000:1000"
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - ./zoominvitr.data/app:/data
      - ./zoominvitr.data/logs:/logs

  redis:
    image: redis:7-alpine
    container_name: zoominvitr_db
    user: "1000:1000"
    restart: on-failure
    # Redis Options
    # https://stackoverflow.com/a/74031727
    # https://raw.githubusercontent.com/redis/redis/7.0/redis.conf
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./zoominvitr.data/database:/data